<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE program [ 
  <!ELEMENT program (tac+)>
  <!ELEMENT tac (dst?,src1?,src2?)>
  <!ELEMENT dst (#PCDATA)>
  <!ELEMENT src1 (#PCDATA)>
  <!ELEMENT src2 (#PCDATA)>
  <!ATTLIST program name CDATA #IMPLIED>
  <!ATTLIST tac opcode CDATA #REQUIRED>
  <!ATTLIST tac order CDATA #REQUIRED>  
  <!ATTLIST dst type (integer|string|variable|label) #REQUIRED>
  <!ATTLIST src1 type (integer|string|variable) #REQUIRED>
  <!ATTLIST src2 type (integer|string|variable) #REQUIRED>
  <!ENTITY language "IPPeCode">
  <!ENTITY eol "&#xA;">
  <!ENTITY lt "&lt;">
  <!ENTITY gt "&gt;">
]>
<program name="Project introduction 1: Print numbers from 1 to 5 (using &language;)">
  <tac opcode="MOV" order="1">
    <dst type="variable">n</dst>
    <src1 type="integer">0</src1>
  </tac>
  <tac opcode="LABEL" order="2">
    <dst type="label">@START</dst>
  </tac>
  <tac opcode="JUMPIFEQ" order="3">
    <dst type="label">@END</dst>
    <src1 type="variable">n</src1>
    <src2 type="integer">5</src2>
  </tac>
  <tac opcode="ADD" order="4">
    <dst type="variable">n</dst>
    <src1 type="variable">n</src1>
    <src2 type="integer">1</src2>
  </tac>
  <tac opcode="PRINT" order="5">
    <src1 type="variable">n</src1>
  </tac>
  <tac opcode="JUMP" order="6">
    <dst type="label">@START</dst>
  </tac>
  <tac opcode="LABEL" order="7">
    <dst type="label">@END</dst>
  </tac>
</program> 